# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: check into main
        run: |
            ssh -q -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
              cd /home/ubuntu/thinkering/le-ou-la-vite
              ./bin/into_main.sh
            EOF

      - name: pnpm install
        run: |
            ssh -q -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
              cd /home/ubuntu/thinkering/le-ou-la-vite
              pnpm install
            EOF

      - name:  pnpm build
        run: |
            ssh -q -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
              cd /home/ubuntu/thinkering/le-ou-la-vite
              pnpm build
            EOF

      - name: Restart Backend
        run: |
            ssh -q -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
              cd /home/ubuntu/thinkering/le-ou-la-vite
              ./bin/symlink_service.sh
              ./bin/restart_service.sh
            EOF